name: ji_mobile_app
description: This corresponds to the app mobile for the RI

publish_to: "none" 

version: 1.0.0+22

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.1
  json_annotation: ^3.0.1
  cupertino_icons: ^0.1.3
  form_field_validator: ^1.0.1
  string_validator: ^0.1.4
  progress_dialog: ^1.2.4
  flutter_svg: ^0.18.0
  rflutter_alert: ^1.0.3
  dio: ^3.0.9
  responsive_value: ^0.0.2
  flutter_staggered_grid_view: ^0.3.1
  expandable: ^4.1.4
  sqflite: ^1.3.0
  shared_preferences: ^0.5.10
  intl: ^0.16.0
  adaptive_action_sheet: ^1.0.5
  validators: ^2.0.0+1
  smooth_page_indicator: ^0.2.0
  mask_text_input_formatter: ^1.0.7
  url_launcher: ^5.7.5
  flutter_markdown: ^0.4.4
  flutter_dialogs: ^1.1.0
  device_info_plus: ^0.5.0
  simple_mustache: ^1.0.0
  screenshot: ^0.2.0
  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  sweetsheet: ^0.2.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  mockito: ^4.1.1
  args: ^1.6.0
  code_builder: ^3.4.0
  test_coverage: ^0.4.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #assets:
    #- assets/images/
    #- assets/i18n/
    #- assets/test_i18n/
    #- assets/files/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
